version: '3.8'

services:
  frontend:
    container_name: design
    image: design
    build:
      target: development
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
